version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://banking_db_user@postgres/banking_db
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: banking_db_user
      POSTGRES_DB: banking_db